version: '3'

services:
  influx:
    image: influxdb
    environment:
        INFLUXDB_DB: cadvisor
    volumes:
      - influx:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.10"
          memory: "128M"
        reservations:
          cpus: "0.05"
          memory: "64M"
    networks:
      - monitoring          

  grafana:
    image: grafana/grafana
    environment:
        DS_NAME: InfluxDB
        DS_TYPE: InfluxDB
        DS_ACCESS: proxy
        DS_URL: http://influx:8086
        DS_DB: cadvisor
    ports:
      - 0.0.0.0:80:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.10"
          memory: "128M"
        reservations:
          cpus: "0.05"
          memory: "64M"
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.10"
          memory: "128M"
        reservations:
          cpus: "0.05"
          memory: "64M"
    networks:
      - monitoring          

volumes:
  influx:
    driver: local
  grafana:
    driver: local
    
networks:
  monitoring:
