version: '3'

services:

  elasticsearch:version: '3'

services:
  elasticsearch:
    #build: elasticsearch/
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.6.3'
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    deploy:
      placement:
        constraints: [node.role == worker]      

  logstash:
    #build: logstash/
    image: 'docker.elastic.co/logstash/logstash:5.6.3'
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.role == worker]            

  kibana:
    #build: kibana/
    image: 'docker.elastic.co/kibana/kibana:5.6.3'
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.role == manager]     
