version: '3'

services:
    data_collector:
        image: beia/data_collector
        environment:
          CONFIG: config
        depends_on:
         - config
         - web
         - graphite
        networks:
         - config
         - web
         - data
    graphite:
        image: vladwing/graphite
        volumes:
         - graphite_data:/var/spool/graphite
        networks:
         - config
         - web
         - data
    alerter:
        image: beia/alerter
        environment:
          CONFIG: config
        depends_on:
         - sip_notifier
         - config
         - web
        networks:
         - config
         - web
         - data
    config:
        image: beia/config_manager
        environment:
         TOSCA_URL: ${TOSCA_URL:-http://www.google.com}
        networks:
         - config
    web:
        image: beia/nginx_proxy
        environment:
          CONFIG: config
        ports:
         - "8880:80/tcp"
        depends_on:
         - graphite
         - alerter
         - data_collector
        networks:
         - config
         - web
    sip_notifier:
        image: beia/sip_notifier
        environment:
          CONFIG: config
        networks:
         - config
         - data
volumes:
 graphite_data:
networks:
 sip_internal:
 config:
 data:
 web:
