version: "3"
 
services:
 
  udp_server:
    image: ubuntu:16.04
    #command: bash -c "apt-get update && apt-get install -y iperf net-tools iputils-ping&& iperf -s -u -B 192.168.2.255 -i 1"
    command: bash -c "apt-get update && apt-get install -y iperf net-tools iputils-ping&& tail -f /dev/null"    
    networks:
      - app  
    
  client:
    image: ubuntu:16.04
    depends_on:
      - udp_server
    #command: bash -c "apt-get update -y && apt-get install socat -y && sleep 5 && while true; do echo "Sending" ; date | socat - udp-datagram:192.168.2.255:5001,broadcast; sleep 0.5; done;"
    command: bash -c "apt-get update && apt-get install -y iperf net-tools iputils-ping&& tail -f /dev/null"    
    networks:
      - app         
        
        
        
networks:
    app:
        driver: weaveworks/net-plugin:latest_release
        driver_opts:
            works.weave.multicast: "1"