version: "3.2"

services:


  adapter:
    ports:
      - target: 8125
        published: 8125
        protocol: udp
        mode: ingress
    image: beia/monitoring_adapter
    environment:
      - MONITORING_SERVER=194.249.1.175
      - MONITORING_PREFIX=eu.switch.mog
      - LOGGING_LEVEL=trace
      - GRAPHITE_SERVER=pc-vfilipe
    networks:
      - app_mog


  input1:
    ports:
      - target: 2000
        published: 2000
        protocol: udp
        mode: ingress
    environment:
      - inPort=2000
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3000
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input1
      - identification=InputDistributor1
      - metrics=true
      - adapterip=adapter
    image: mogpsantos/inputpipe
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog

  input2:
    ports:
      - target: 2002
        published: 2002
        protocol: udp
        mode: ingress
    environment:
      - inPort=2002
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3002
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input2
      - identification=InputDistributor2
      - metrics=true
      - adapterip=adapter
    image: mogpsantos/inputpipe
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog


  input3:
    ports:
      - target: 2004
        published: 2004
        protocol: udp
        mode: ingress
    environment:
      - inPort=2004
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3004
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input3
      - identification=InputDistributor3
      - metrics=true
      - adapterip=adapter
    image: mogpsantos/inputpipe
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog

  input4:
    ports:
      - target: 2006
        published: 2006
        protocol: udp
        mode: ingress
    environment:
      - inPort=2006
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3006
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input4
      - identification=InputDistributor4
      - metrics=true
      - adapterip=adapter
    image: mogpsantos/inputpipe
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog



################################################



  proxy1:
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: ingress
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3000
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy1
      - identification=ProxyTranscoder1
      - metrics=true
      - videoswitcherip=switcher
      - adapterip=adapter
    image: mogpsantos/proxytranscoder
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog


  proxy2:
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3002
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy2
      - identification=ProxyTranscoder2
      - metrics=true
      - videoswitcherip=switcher
      - adapterip=adapter
    image: mogpsantos/proxytranscoder
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog


  proxy3:
    ports:
      - target: 80
        published: 8083
        protocol: tcp
        mode: ingress
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3004
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy3
      - identification=ProxyTranscoder3
      - metrics=true
      - videoswitcherip=switcher
      - adapterip=adapter
    image: mogpsantos/proxytranscoder
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog



  proxy4:
    ports:
      - target: 80
        published: 8084
        protocol: tcp
        mode: ingress
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3006
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy4
      - identification=ProxyTranscoder4
      - metrics=true
      - videoswitcherip=switcher
      - adapterip=adapter
    image: mogpsantos/proxytranscoder
    depends_on:
      - input4
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog


  proxyOut:
    ports:
      - target: 80
        published: 8085
        protocol: tcp
        mode: ingress
    environment:
      - multicastAddrIP=226.2.2.2
      - multicastAddrPort=6000
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=corona
      - identification=ProxyTranscoderOut
      - metrics=true
      - videoswitcherip=switcher
      - adapterip=adapter
    image: mogpsantos/proxytranscoder
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog

#####################################################

  switcher:
    ports:
      - target: 6000
        published: 6000
        protocol: udp
        mode: ingress
      - target: 8008
        published: 8008
        protocol: tcp
        mode: ingress
    environment:
      # MulticastGroups
      - multicastAddrIP=225.2.2.0
      # Multicast Port
      - multicastAddrPort=3000
      - multicastAddrPort2=3002
      - multicastAddrPort3=3004
      - multicastAddrPort4=3006
      # SWITCHER SETTINGS
      - switcherOutAddrIP=226.2.2.2
      - switcherOutAddrPort=6000
      - switcherREST=8008
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=switvher
      - identification=VideoSwitcher
      - metrics=true
      - buffer=true
      - camnumber=4
      - adapterip=adapter
      - synctime=120
    image: mogpsantos/videoswitcher
    networks:
      - app_mog


####################################################



  output:
    ports:
      - target: 4000
        published: 4000
        protocol: udp
        mode: ingress
    environment:
      - multicastAddrIP=226.2.2.2
      - multicastAddrPort=6000
      - videoWidth=720
      - videoHeight=406
      - OutIP=10.20.130.1
      - OutPort=4000
      - statsdPort=8125
      - machineip=output
      - identification=OutputTranscoder
      - metrics=true
      - adapterip=adapter
    image: mogpsantos/outputtranscoder
    volumes:
      - type: tmpfs
        target: /ram
    networks:
      - app_mog

  frontend:
    ports:
      - target: 80
        published: 5050
        protocol: tcp
        mode: ingress
    image: mogpsantos/switchgui
    environment:
      - ipPT1=proxy1
      - ipPT2=proxy2
      - ipPT3=proxy3
      - ipPT4=proxy4
      - ipPTout=proxyOut
      - ipVS=switcher
    networks:
      - app_mog

networks:
    app_mog:
        driver: weaveworks/net-plugin:latest_release
        driver_opts:
            works.weave.multicast: "1"

