# File to run on a remote machine with access to mog's registry (mogswitch)

version: "3.2"

services:

  streamer:
    environment:
      - inPort=2000
      - inPort2=2002
      - inPort3=2004
      - inPort4=2006
      - ipID1=input
      - ipID2=input2
      - ipID3=input3
      - ipID4=input4
      - camnumber=4
    image: mogpsantos/streamer
    networks:
      - app            



  input:
    ports:
      - "2000:2000/udp"
    environment:
      - inPort=2000
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3000
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input
      - identification=InputDistributor1
      - metrics=true
    image: mogpsantos/inputpipe
    #tmpfs:
     #- /ram/ 
    volumes:
      - type: tmpfs
        target: /ram         
    networks:
      - app                    

  input2:
    ports:
      - "2002:2002/udp"
    environment:
      - inPort=2002
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3002
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input2
      - identification=InputDistributor2
      - metrics=true
    image: mogpsantos/inputpipe
    #tmpfs:
     #- /ram/     
    volumes:
      - type: tmpfs
        target: /ram        
    networks:
      - app                    



  input3:
    ports:
      - "2004:2004/udp"
    environment:
      - inPort=2004
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3004
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input3
      - identification=InputDistributor3
      - metrics=true
    image: mogpsantos/inputpipe
    #tmpfs:
     #- /ram/
    volumes:
      - type: tmpfs
        target: /ram   
    networks:
      - app                    
        
  input4:
    ports:
      - "2006:2006/udp"
    environment:
      - inPort=2006
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3006
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=input4
      - identification=InputDistributor4
      - metrics=true
    image: mogpsantos/inputpipe
    #tmpfs:
     #- /ram/
    volumes:
      - type: tmpfs
        target: /ram       
    networks:
      - app                    



################################################



  proxy:
    ports:
      - "8081:80"
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3000
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy
      - identification=ProxyTranscoder1
      - metrics=true
    image: mogpsantos/proxytranscoder
    depends_on:
      - input
    #tmpfs:
     #- /ram/    
    volumes:
      - type: tmpfs
        target: /ram     
    networks:
      - app                    

  proxy2:
    ports:
      - "8082:80"
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3002
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy2
      - identification=ProxyTranscoder2
      - metrics=true
    image: mogpsantos/proxytranscoder
    depends_on:
      - input2
    #tmpfs:
     #- /ram/      
    volumes:
      - type: tmpfs
        target: /ram     
    networks:
      - app                    


  proxy3:
    ports:
      - "8083:80"
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3004
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy3
      - identification=ProxyTranscoder3
      - metrics=true
    image: mogpsantos/proxytranscoder
    depends_on:
      - input3    
    #tmpfs:
     #- /ram/
    volumes:
      - type: tmpfs
        target: /ram      
    networks:
      - app                    



  proxy4:
    ports:
      - "8084:80"
    environment:
      - multicastAddrIP=225.2.2.0
      - multicastAddrPort=3006
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxy4
      - identification=ProxyTranscoder4
      - metrics=true
    image: mogpsantos/proxytranscoder
    depends_on:
      - input4    
    #tmpfs:
     #- /ram/
    volumes:
      - type: tmpfs
        target: /ram       
    networks:
      - app                    


  proxyOut:    
    ports:
      - "8085:80"
    environment:
      - multicastAddrIP=226.2.2.2
      - multicastAddrPort=6000
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=proxyOut
      - identification=ProxyTranscoderOut
      - metrics=true
    image: mogpsantos/proxytranscoder
    depends_on:
      - switcher    
    #tmpfs:
     #- /ram/
    volumes:
      - type: tmpfs
        target: /ram       
    networks:
      - app                    

#####################################################

  switcher:
    ports:
      - "8008:8008"
    environment:
      # MulticastGroups
      - multicastAddrIP=225.2.2.0
      # Multicast Port
      - multicastAddrPort=3000
      - multicastAddrPort2=3002
      - multicastAddrPort3=3004
      - multicastAddrPort4=3006
      # SWITCHER SETTINGS
      - switcherOutAddrIP=226.2.2.2
      - switcherOutAddrPort=6000
      - switcherREST=8008
      - waitingTime=5
      - videoWidth=720
      - videoHeight=406
      - statsdPort=8125
      - machineip=switcher
      - identification=VideoSwitcher
      - metrics=true
      - buffer=false
      - camnumber=4
    image: mogpsantos/videoswitcher
    networks:
      - app                


####################################################



  output:
    ports:
      - "4000:4000"
    environment:
      - multicastAddrIP=226.2.2.2
      - multicastAddrPort=6000
      - videoWidth=720
      - videoHeight=406
      - OutIP=127.0.0.1
      - OutPort=4000
      - statsdPort=8125
      - machineip=output
      - identification=OutputTranscoder
      - metrics=true
    image: mogpsantos/outputtranscoder
    #tmpfs:
     #- /ram/     
    volumes:
      - type: tmpfs
        target: /ram        

  frontend:
    ports:
      - "5050:80"
    image: mogpsantos/switchgui
    environment:
      - ipPT1=proxy
      - ipPT2=proxy2
      - ipPT3=proxy3
      - ipPT4=proxy4
      - ipPTout=proxyOut
      - ipVS=switcher
    networks:
      - app                  
      
#######################Monitoring########################################      
  adapter:
    ports:
      - "8125:8125/udp"
    image: beia/monitoring_adapter
    environment:
      - MONITORING_SERVER=monitoring_server
      - MONITORING_PREFIX=eu.switch.mog
      - LOGGING_LEVEL=debug 
    networks:
      - app                  
      
      
  monitoring_server:
    image: salmant/ul_monitoring_server_container_image2 # salmant/salman_monitoring_server_container_image
    ports:
      - "8080:8080"
      - "4242:4242"
      - "4245:4245"
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
      - "9042:9042"
      - "8012:8012"
      - "61621:61621"
    environment:
      - MONITORING_SERVER=monitoring_server     
    networks:
      - app                  
      
networks:  
  app:
