---
- hosts: all
  tasks:
  
  - name: install pre-req
    apt: name="{{ item }}" update_cache=yes state=latest upgrade=yes
    with_items: [python, tcsh, curl, python-pip,apt-transport-https]
    become: true
    
  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: install pre-req
    apt: name="{{ item }}" update_cache=yes state=latest upgrade=yes
    with_items: [docker-ce]
    become: true
    
    - pip:
      name: docker-compose
      
    - {name: download compose, command: curl -o /usr/local/bin/docker-compose -L "https://github.com/docker/compose/releases/download/1.17.1/docker-compose-$(uname -s)-$(uname -m)"
  , become: true}
  
    - {name: set x , command:   chmod +x /usr/local/bin/docker-compose, become: true}
