---
- hosts: all
  tasks:
  - name: Update aptitude
    apt: {name: aptitude}
    become: true
    register: result
    
  - name: update and upgrade
    apt: {update_cache: true, upgrade: true, autoremove: true, force: true}
    become: true
    register: result    
    
  - name: install pre-req
    apt: name="{{ item }}" state=latest
    with_items: [python, curl, python-pip, apt-transport-https, linux-image-extra-virtual,
      linux-image-extra-4.4.0-97-generic, ca-certificates, software-properties-common]
    become: true
    register: result
    
  - name: Add key
    apt_key: {url: 'https://download.docker.com/linux/ubuntu/gpg', state: present}
    become: true
    register: result   
    
  - name: add repo
    apt_repository: {repo: 'deb https://download.docker.com/linux/ubuntu xenial stable', state: present}
    become: true
    register: result      
    
  - name: update and upgrade
    apt: {update_cache: true, upgrade: true, autoremove: true, force: true}
    become: true
    register: result
    
  - name: install docker-ce
    apt: name="{{ item }}" state=latest
    with_items: [docker-ce]
    become: true
    register: result
    
  - name: download compose
    get_url: {url: 'https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64',
      dest: /usr/local/bin/docker-compose, mode: 488}
    become: true
    register: result
    
  - name: download compose file
    get_url: {url: 'https://raw.githubusercontent.com/QCAPI-DRIP/DRIP-integration/master/docker-composer/MOG/docker-compose.yml', dest: /tmp/docker-compose.yml}
    register: result
        
  - pip:
        name: docker-py    
    become: true   
    
  - name: docker plugin install
    command: 'docker plugin install --grant-all-permissions weaveworks/net-plugin:latest_release'
    become: true
    ignore_errors: yes
    
  - name: docker plugin disable
    command: 'docker plugin disable weaveworks/net-plugin:latest_release'
    become: true
    ignore_errors: yes
    
  - name: docker plugin set
    command: 'docker plugin set weaveworks/net-plugin:latest_release WEAVE_MULTICAST=1'
    become: true
    ignore_errors: yes
    
  - name: docker plugin enable
    command: 'docker plugin enable weaveworks/net-plugin:latest_release'
    become: true
    ignore_errors: yes
    
  - name: docker swarm init
    command: 'docker swarm init'
    become: true
    ignore_errors: yes
    
  - {name: docker-compose, command: docker-compose -f /tmp/docker-compose.yml up -d, become: true}
